pipeline {
    agent {
         docker {
            image 'kdilipkumar/jenkins-agent:v19'
            args '--user root -v /var/run/docker.sock:/var/run/docker.sock'
        }
    }

    environment {
        DOCKER_IMAGE = "kdilipkumar/backend:v${BUILD_NUMBER}"
    }
    
    stages {
        stage('Cleanup') {
            steps {
                sh 'rm -rf expense-project || true'
            }
        }

        stage('Checkout Repository') {
            steps {
                sh '''
                    echo "Cloning repository..."
                    git clone https://github.com/Dilip-Devopos/expense-project.git
                '''
            }
        }

        stage('Setup & Build Web') {
            steps {
                sh 'cd expense-project/backend && mvn clean package -DskipTests'
            }
        }

        stage('Archive Build Artifacts') {
            steps {
                archiveArtifacts artifacts: 'expense-project/backend/target/*.jar', fingerprint: true
            }   
        }

        stage('Static Code Analysis') {
            environment {
                SONAR_URL = "http://192.168.0.180:9000"
            }
            steps {
                withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_AUTH_TOKEN')]) {
                    sh '''
                        cd expense-project/backend
                        mvn sonar:sonar -Dsonar.login=$SONAR_AUTH_TOKEN -Dsonar.host.url=${SONAR_URL}
                    '''
                }
            }
        }

        stage('Download Latest Artifact and Verify') {
            steps {
                script {
                    sh '''
                        # Define source and destination paths
                        WAR_FILE=$(ls -t expense-project/backend/target/*.jar | head -n 1)
                        
                        # Copy the WAR file to the required location
                        cp "$WAR_FILE" /home/jenkins/download_artifact

                        # List files to verify the copy operation
                        ls /home/jenkins/download_artifact
                    '''
                }
            }
        }

        stage('OWASP Dependency-Check Vulnerabilities') {
            steps {
                script {
                    sh '''
                        /opt/dependency-check/bin/dependency-check.sh \
                        --project "expense-project" \
                        --scan /home/jenkins/download_artifact/*.jar \
                        --out dependency-check-reports \
                        --format "XML"
                    '''
                    sh 'chown -R jenkins:jenkins dependency-check-reports'
                    sh 'chmod 644 dependency-check-reports/*.xml'
                    sh 'ls -la dependency-check-reports'
                }
                dependencyCheckPublisher pattern: 'dependency-check-reports/*.xml'
            }
        }

        stage('Build Docker Image') {
            environment {
                DOCKERFILE_LOCATION = "expense-project/backend/Dockerfile"
            }
            steps {
                script {
                    sh 'cd expense-project/backend && docker build -t ${DOCKER_IMAGE} .'
                }
            }
        }

        stage('Security Scan with Trivy') {
            steps {
                script {
                    sh '''
                        echo "Running Trivy vulnerability scan..."
                        trivy --version
                        trivy image --severity HIGH,CRITICAL ${DOCKER_IMAGE}
                    '''
                }
            }
        }

        stage('Push Docker Image') {
            environment {
                REGISTRY_CREDENTIALS = credentials('docker-cred')
            }
            steps {
                script {
                    def dockerImage = docker.image("${DOCKER_IMAGE}")
                    docker.withRegistry('https://index.docker.io/v1/', "docker-cred") {
                        dockerImage.push()
                    }
                }
            }
        }
    }
}
